CREATE TABLE owners(
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    phone_number VARCHAR(15) NOT NULL,
    address VARCHAR(50)
);
CREATE TABLE animal_types(
    id SERIAL PRIMARY KEY,
    animal_type VARCHAR(30) NOT NULL
);
CREATE TABLE cages(
    id SERIAL PRIMARY KEY,
    animal_type_id INTEGER REFERENCES animal_types(id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL
);
CREATE TABLE animals(
    id SERIAL PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    birthdate DATE NOT NULL,
    owner_id INTEGER REFERENCES owners(id) ON DELETE CASCADE ON UPDATE CASCADE,
    animal_type_id INTEGER REFERENCES animal_types(id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL
);
CREATE TABLE volunteers_departments(
    id SERIAL PRIMARY KEY,
    department_name VARCHAR(30) NOT NULL
);
CREATE TABLE volunteers(
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    phone_number VARCHAR(15) NOT NULL,
    address VARCHAR(50),
    animal_id INTEGER REFERENCES animals(id) ON DELETE CASCADE ON UPDATE CASCADE,
    department_id INTEGER REFERENCES volunteers_departments(id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL
);
CREATE TABLE animals_cages(
    cage_id INTEGER REFERENCES cages ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
    animal_id INTEGER REFERENCES animals(id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL 
);